version: "3.9"
services:

  # SQL database
  db:
    image: "postgres:13-alpine"
    restart: "always"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_SCHEMA}"

  api:
    build:
      context: .
      args:
        ENVIRONMENT: "${ENVIRONMENT}"
        SECRET: "${SECRET}"
        DATABASE_USER: "${DATABASE_USER}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
        DATABASE_HOST: "${DATABASE_HOST}"
        DATABASE_PORT: "${DATABASE_PORT}"
        DATABASE_SCHEMA: "${DATABASE_SCHEMA}"
    ports:
      - "8080:8080"
    links:
      - "db:db"
    depends_on:
      - "db"
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      SECRET: "${SECRET}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_SCHEMA: "${DATABASE_SCHEMA}"


volumes:
  db-data:
