version: "3.9"
services:

  # SQL database
  db:
    image: "postgres:13-alpine"
    restart: "always"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "public"

  api:
    build: .
    ports:
      - "8080:8080"
    links:
      - "db"
    depends_on:
      - "db"
    environment:
      SECRET: "26fca5a53f91a32f73e236c076a48e13173f17d7984d7a38086c69d4c960712d"
      DATABASE_USER: "testuser"
      DATABASE_PASSWORD: "mpassword"
      DATABASE_URL: ""


volumes:
  db-data: