version: "2.1"
services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_SCHEMA}

  api:
    build:
      context: .
      args:
        ENVIRONMENT: "${ENVIRONMENT}"
        SECRET: "${SECRET}"
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      SECRET: "${SECRET}"
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}


volumes:
  db-data:
