name: Push Container to Heroku

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  ENVIRONMENT: ''
  SECRET: ''
  DATABASE_USER: ''
  DATABASE_PASSWORD: ''
  DATABASE_HOST: ''
  DATABASE_PORT: ''
  DATABASE_SCHEMA: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Env
        run: echo ${{ env.heroku-prod.ENVIRONMENT }}
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web